# Eigenvalue equations

#### Excercise 1
 Write a program that uses the [QR algorithm][1] to find the eigenvlues of a $4\times4$ matrix $A$, with random elements but known eignevalues. You can create such a matrix by $A=SDS^{-1}$, where $D$ is a diagonal matrix with the expected eigenvalues on the diagonal, and $S$ is any random matrix of the same size.

Stop the QR algorithm iteration process when the element in the lower left corner become extremely small, $|A_{3,0}| <10^{-300}$ Note that it is unlikely the upper triangluar part of the matrix will be zero. 

- Print out the oringal and finished matrix $A$
- Verify the diagonal of $A$ has the same elements that are found with [`numpy.linalg.eig`][2]. Use  [`numpy.diagonal`][3] to view only the diagonal of $A.



[1]: https://en.wikipedia.org/wiki/QR_algorithm
[2]: https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.linalg.eig.html
[3]: https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html

<div class="alert alert-block alert-info">
<b>Tip:</b> Note that the results may not come out in the same order, but you should expect that the eigenvectors should match their respective eigenvalues.
</div>

In [14]:
import numpy 
import scipy.linalg



A = numpy.random.rand(4,4)
print(A)

d,P = scipy.linalg.eig(A)
D = numpy.dot(scipy.linalg.inv(P),numpy.dot(A,P))


print(f"Eigenvalues of A are : {d}")
print(f"Diagonal of P_inv: {numpy.diagonal(D)}")


D4 = numpy.power(D,4)
A4 = numpy.dot(P,numpy.dot(D4,scipy.linalg.inv(P)))
A4 = numpy.linalg.matrix_power(A,4)

print(A4)

[[0.8462836  0.09960822 0.15483009 0.20173911]

 [0.05119221 0.64273684 0.27159681 0.41192032]

 [0.22285865 0.9519866  0.88535879 0.15042772]

 [0.82037129 0.42148904 0.57193991 0.55984442]]

Eigenvalues of A are : [1.75695945+0.j         0.76759864+0.j         0.20483278+0.20832639j

 0.20483278-0.20832639j]

Diagonal of P_inv: [1.75695945+2.04472070e-32j 0.76759864+3.25908152e-32j

 0.20483278+2.08326391e-01j 0.20483278-2.08326391e-01j]

[[1.71192532 1.70123825 1.47810081 1.05442651]

 [1.92041967 2.53754666 2.10450804 1.46465611]

 [2.74683435 4.05528207 3.29500097 2.2806248 ]

 [3.29602289 3.94153352 3.31191348 2.31712149]]


<font color="blue">Answer:</font>

#### Excercise 2

The `scipy` functions for solving eigenvalue problems are `scipy.linalg.eig` and `scipy.linalg.eigh`.

What is the difference between these functions? Provide a definition for all terms.

<font color="blue">Answer: <font>
    
    - scipy.linalg.eigh guarantees you that the eigenvalues are sorted and uses a faster algorithm 
    that takes advantage of the fact that the matrix is symmetric. 
    If you know that your matrix is symmetric, use this function.

    - escipy.linalg.eigh doesn't check if your matrix is indeed symmetric, it by default just takes 
    the lower triangular part of the matrix and assumes that the upper triangular part is defined 
    by the symmetry of the matrix.

    - scipy.linalg.eig works for general matrices and therefore uses a slower algorithm. 
    If you test with larger matrices, you will also see that in general 
    the eigenvalues are not sorted here.

#### Excercise 3
Use specifically the `scipy.linalg.eigh` function to find the eigenvaleus and eignevectors of the matrix
$$\begin{bmatrix}
1 & 0 \\
2 & 1
\end{bmatrix}$$
Did you get the same or different results from the lecture example 2? Is that correct? Why is that?

In [19]:
A = numpy.array([[1,0],[2,1]],dtype=float)
Y,V = scipy.linalg.eigh(A)
print(Y)
print(V)

[-1.  3.]

[[-0.70710678  0.70710678]

 [ 0.70710678  0.70710678]]


<font color="blue"> Answer: </font> 

#### Excercise 4
Use and eigenproblem solver to find the eigenvalues of the matrix
$$\begin{bmatrix}
-2 & +2 & -3\\
+2 & +1 & -6\\
-1 & -2 & +0
\end{bmatrix}$$
Verify you get the eigenvalues $\lambda=-3,-3,$ and $5$. 

- Verify that the eigenvector for $\lambda=5$ is proportional to
$$
\frac{1}{\sqrt{6}}\left[
\begin{array}{}+1\\+2\\-1\end{array}
\right]
$$

The eigenvalue $-3$ corresponds to a double root. This means that the corresponding eigenvectors are degenerate, which in turn means that they are not unique. Here are two linearly independent ones:
$$
\frac{1}{\sqrt{5}}\left[
\begin{array}{}+2\\-1\\+0\end{array}
\right], \ \ 
\frac{1}{\sqrt{10}}\left[
\begin{array}{}-3\\+0\\-1\end{array}
\right]
$$
In this case it’s not clear what the `scipy.linalg.eig` solver will give for these eigenvectors, it probably won't be these.

- Try to find a relationship between *your* computed eigenvectors for the eigenvalues of $−3$ and these two linearly independent ones provided above.
    

In [22]:
A = numpy.array([[-2,2,-3],
                 [2,1,-6],
                 [-1,-2,0]],dtype=float)

Y,V = numpy.linalg.eig(A)
print(Y)
print(V)

[-3.  5. -3.]

[[-0.95257934  0.40824829 -0.02296692]

 [ 0.27216553  0.81649658  0.83534731]

 [-0.13608276 -0.40824829  0.54924256]]


#### Excercise 5
The kinetc energy of an object rotating about the angular velocity vector $\vec{\omega}$ is $K=\frac{1}{2}\vec{\omega}\pmb{I}\vec{\omega}$, where $\pmb{I}$ is the inertia tensor. For a solid cube of mass $m$ and side $s$, whose geometric center is the at the origin of space, 
$$
\pmb{I} = \frac{Ms^2}{6}\begin{bmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{bmatrix}
$$
and it will rotate easily about any of its principle axes parallel to its sides. ($\pmb{I}$ is already diagonal!)

If we shift the point of rotation to a corner of the cube by moving the cube $\vec{a}=(-s/2, -s/2, -s/2)$, then the inertia tensor is 
$$
I'_{ij} = I_{ij}+M\left[\delta_{ij}a^2-a_ia_j\right]
$$

- Write down the new inertia tensor using $\LaTeX$ in a Markdown cell.
    
This inertia tensor is not diagonal anymore, so if you start the cube rotating about a corner, and if the axis of rotation is one of the edges of the cube, it will tumble out of control along its new principle axes of rotation. For any rotating mechanical part, it is important that it rotate about a principal axis, otherwise it will exert a torque and cause vibrations.

- Find the principle axes of rotation as the eigenvectors of $\pmb{I}'$.
- Verify that any two eigenvectors are orthogonal, and are normal.

<font color="blue">Answer: <font>

In [23]:
I=numpy.array([[1,0,0],
              [0,1,0],
              [0,0,1]],dtype=float)
Y,V= scipy.linalg.eigh(I)
print(Y)
print(V)

[1. 1. 1.]

[[1. 0. 0.]

 [0. 1. 0.]

 [0. 0. 1.]]
